DROP TABLE IF EXISTS dono;
DROP TABLE IF EXISTS pet;

CREATE TABLE dono (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	cpf TEXT UNIQUE NOT NULL,
	nome_dono TEXT NOT NULL,
	senha TEXT NOT NULL
);

CREATE TABLE pet (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	dono_id INTEGER,
	nome TEXT NOT NULL,
	especie TEXT NOT NULL,
	raca TEXT,
	idade INTEGER,
	criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (dono_id) REFERENCES dono (id)
);